spring:
    data:
        mongodb:
                database: taxService
                

    output:
        ansi:
            enabled: ALWAYS                             

# setting the logging level
logging:
    level:
        com:
            skillstorm: debug               # sets the logging level for the entire package
