spring:
    config:
        import: 
             env.yml
             
    data:
        mongodb:
                #uri: ${MONGO_CONNECT}
                uri: ${AWS_CONNECT}
                #database: ${MONGO_DB}
                database: ${AWS_DB}
                
    output:
        ansi:
            enabled: ALWAYS            

    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: ${OATH2_CLIENT}
                        clientSecret: ${OATH2_SECRET}
                        
javax:
    net:
        ssl:
            trustStore: ${TRUST_STORE}
            trustStorePassword: ${TRUST_STORE_PS}
                                                                         
# setting the logging level
logging:
    level:
        com:
            skillstorm: debug               # sets the logging level for the entire package
