spring:
    #datasource:

    output:
        ansi:
            enabled: ALWAYS

server:
    port: 8080                              

# setting the logging level
logging:
    level:
        com:
            skillstorm: debug               # sets the logging level for the entire package
