spring:
    data:
        mongodb:
                uri: mongodb+srv://user01:9H1LxdhbxNjgf3j9@taxservice.soyqc0g.mongodb.net/?retryWrites=true&w=majority
                database: taxService
                

    output:
        ansi:
            enabled: ALWAYS                             

# setting the logging level
logging:
    level:
        com:
            skillstorm: debug               # sets the logging level for the entire package
